name: Mass Scrape Ping

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Mass Scrape Wikipedia"]
    types: [completed]

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Wait
        run: sleep 15
